echo "Downloading jacov-maven-plugin.jar"
curl -o jacov-maven-plugin.jar "https://kr.object.ncloudstorage.com/caas-dev-bucket/download/jacov-maven-plugin.jar"
echo "Complete download. (jacov-maven-plugin)"
echo "Downloading java-runtime.jar"
curl -o java-runtime.jar "https://kr.object.ncloudstorage.com/caas-dev-bucket/download/java-runtime.jar"
echo "Complete download. (java-runtime)"

echo "Install maven plugins (jacov-maven-plugin)"
mvn install:install-file -Dfile="jacov-maven-plugin.jar" -DgroupId=com.qualityscroll.caas -DartifactId=jacov-maven-plugin -Dpackaging="jar" -Dversion="1.0.0-SNAPSHOT"
echo "Complete installation. (jacov-maven-plugin)"
echo "Install java runtime (java-runtime)"
mvn install:install-file -Dfile="java-runtime.jar" -DgroupId=com.qualityscroll.caas -DartifactId=java-runtime -Dpackaging="jar" -Dversion="0.0.1-SNAPSHOT"
echo "Complete installation. (java-runtime)"
